systematicsAndShapes = {
 "yields": { # This always needs to be defined
           "name": "yields",
           "type": "yieldsWithShapes",
           "file": "[ROOTFILE]_[CHANNEL].root",
           "match": "[VAR]_[CHANNEL]_$PROCESS",
           "extendedABCD": {"SR": "_SR", "B1": "_B1", "B2":"_B2", "C1":"_C1", "C2":"_C2", "D1":"_D1", "D2":"_D2","E1":"_E1", "E2":"_E2"}
 },
 "TrigSF"  : {
            "name": "TrigSF",
            "type": "shape",
            "processes": ["SUEP_.*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
            "corrs": {"RunII":["RunII"]},
 },
 "ElSF"  : {
            "name": "ElSF",
            "type": "shape",
            "processes": ["SUEP_.*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
            "corrs": {"RunII":["RunII"]},
 },
 "MuSF"  : {
            "name": "MuSF",
            "type": "shape",
            "processes": ["SUEP_.*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
            "corrs": {"RunII":["RunII"]},
 },
 "PU"  : {
            "name": "PU",
            "type": "shape",
            "processes": ["SUEP_.*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
            "corrs": {"RunII":["RunII"]},
 },
 "ISR"  : {
            "name": "ISR",
            "type": "shape",
            "processes": ["SUEP_.*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
            "corrs": {"RunII":["RunII"]},
 },
 "FSR"  : {
            "name": "FSR",
            "type": "shape",
            "processes": ["SUEP_.*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
            "corrs": {"RunII":["RunII"]},
 },
 "LFCorr"  : {
            "name": "LFCorr",
            "type": "shape",
            "processes": ["SUEP_.*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
            "corrs": {"RunII":["RunII"]},
 },
 "LFUnCorr"  : {
            "name": "LFUnCorr",
            "type": "shape",
            "processes": ["SUEP_.*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
            "corrs": {"RunII":["RunII"]},

 },
 "HFCorr"  : {
            "name": "HFCorr",
            "type": "shape",
            "processes": ["SUEP_.*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
            "corrs": {"RunII":["RunII"]},
 },
 "HFUnCorr"  : {
            "name": "HFUnCorr",
            "type": "shape",
            "processes": ["SUEP_.*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
            "corrs": {"RunII":["RunII"]},
 },
 "Track"  : {
            "name": "Track",
            "type": "shape",
            "processes": ["SUEP_.*"],
            "match": "$PROCESS",
            "up"  : "_TrackUp",
            "down": "",
            "corrs": {"RunII":["RunII"]},
 },
 "JES"  : {
            "name": "JES",
            "type": "shape",
            "processes": ["SUEP_.*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
            "corrs": {"RunII":["RunII"]},
 },
 "JER"  : {
            "name": "JER",
            "type": "shape",
            "processes": ["SUEP_.*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
            "corrs": {"RunII":["RunII"]},
 },
 "lumi_RunII"  : {
            "name": "lumi",
            "type": "lnN",
            "processes": ["SUEP_.*"],
            "size": {"RunII":[1.016]},
            "corrs": {"RunII":["RunII"]},
 },
 "closure" : {
            "name": "closure",
            "type": "lnN",
            "processes": [".*background.*"],
            "size": 1.2,
            "corrs": {"RunII":["RunII"]},
            "perbin": True,
            "onlychannel": "SR",
 },
}
