systematicsAndShapes = {
 "yields": { # This always needs to be defined
           "name": "yields",
           "type": "yieldsWithShapes",
           "file": "[ROOTFILE]",
           "match": "[VAR]_$PROCESS"
 },
 "ElSF"  : {
            "name": "ElSF",
            "type": "shape",
            "processes": [".*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
 },
 "MuSF"  : {
            "name": "MuSF",
            "type": "shape",
            "processes": [".*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
 },
 "PU"  : {
            "name": "PU",
            "type": "shape",
            "processes": [".*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
 },
 "L1"  : {
            "name": "L1",
            "type": "shape",
            "processes": [".*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
 },
 "ISR"  : {
            "name": "ISR",
            "type": "shape",
            "processes": [".*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
 },
 "FSR"  : {
            "name": "FSR",
            "type": "shape",
            "processes": [".*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
 },
 "LFCorr"  : {
            "name": "LFCorr",
            "type": "shape",
            "processes": [".*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
 },
 "LFUnCorr"  : {
            "name": "LFUnCorr",
            "type": "shape",
            "processes": [".*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
 },
 "HFCorr"  : {
            "name": "HFCorr",
            "type": "shape",
            "processes": [".*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
 },
 "HFUnCorr"  : {
            "name": "HFUnCorr",
            "type": "shape",
            "processes": [".*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
 },
 "Track"  : {
            "name": "Track",
            "type": "shape",
            "processes": [".*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
 },
 "JES"  : {
            "name": "JES",
            "type": "lnN",
            "processes": [".*"],
            "size": 1.01,
 },
 "JER"  : {
            "name": "JER",
            "type": "lnN",
            "processes": [".*"],
            "size": 1.01,
 },
 "lumi"  : {
            "name": "lumi",
            "type": "lnN",
            "processes": [".*"],
            "size": 1.025,
 },
}

